version: '3'

services:
  postgress:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file: .env
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  volumes: ./database/postgres:/data/postgres
ports: "{POSTGRES_PORT}:5432"
